services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - '${PORT:-5555}:3000'
    volumes:
      - .:/app
    depends_on:
      - db

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      POSTGRES_DB: ${DB_DATABASE:-postgres}
    ports:
      - '${DB_FORWARD_PORT:-5432}:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
